[package]
name = "rle-decode-helper"
version = "1.0.0-alpha"
authors = ["Moritz Wanzenböck <moritz.wanzenboeck@catalysts.cc>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[[bench]]
name = "bench"
harness = false

[dependencies]

[dev-dependencies]
criterion = "0.2"
